[package]
name = "any_model_3d_vulkan"
version = "0.2.0"
edition = "2024"

[dependencies]
vulkano = "0.29"
vulkano-shaders = "0.29"
vulkano-win = { version = "0.29", features = ["winit_"] }
winit = "0.26"
cgmath = "0.18"
bytemuck = { version = "1.14", features = ["derive"] }
tobj = "3"
